"""change tests

Revision ID: 705e71a74814
Revises: 0f5092b6ddda
Create Date: 2024-10-18 18:44:24.375097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705e71a74814'
down_revision: Union[str, None] = '0f5092b6ddda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doctors', ['id'])
    op.create_unique_constraint(None, 'patients', ['id'])
    op.add_column('tests', sa.Column('file_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tests', ['id'])
    op.drop_column('tests', 'result')
    op.drop_column('tests', 'date_from')
    op.drop_column('tests', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tests', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('tests', sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tests', type_='unique')
    op.drop_column('tests', 'file_path')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'doctors', type_='unique')
    # ### end Alembic commands ###
