"""add data to tests

Revision ID: 9d1aa4866d35
Revises: 705e71a74814
Create Date: 2024-10-19 10:38:14.481088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1aa4866d35'
down_revision: Union[str, None] = '705e71a74814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('data', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'data')
    # ### end Alembic commands ###
